FROM node:22-alpine AS builder

WORKDIR /app

COPY package*.json ./

RUN npm install

COPY . .

RUN npm run build

CMD ["npm", "run", "start"]

FROM nginx:1.28.0-alpine

COPY --from=builder /app/dist /usr/share/nginx/html

COPY nginx.conf /etc/nginx/conf.d/default.conf

EXPOSE 8080

CMD ["nginx", "-g", "daemon off;"]

# 打包docker镜像
# docker build -t my-blog .

# 运行docker镜像
# docker run -d -p 3000:8080 --name blog my-blog

# 导出docker镜像
# docker save my-blog > my-blog.tar